# Generated by Django 4.0.2 on 2022-02-15 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('ID', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAct',
            fields=[
                ('ID', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDoc',
            fields=[
                ('ID', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID', models.AutoField(max_length=16, primary_key=True, serialize=False)),
                ('nameRS', models.CharField(max_length=200)),
                ('dateIn', models.DateField()),
                ('observation', models.CharField(max_length=200)),
                ('stateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.state')),
                ('typeActID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.typeact')),
                ('typeDocID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.typedoc')),
            ],
        ),
    ]
