# Generated by Django 4.0.2 on 2022-02-16 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movprodserv',
            old_name='ProdServID',
            new_name='prodServID',
        ),
        migrations.RenameField(
            model_name='movprodserv',
            old_name='TypeProdServID',
            new_name='typeProdServID',
        ),
    ]
